/** Generated by scripts/generate-whats-new.mjs from CHANGELOG.md — do not edit. */
export const DERIVED_WHATS_NEW: readonly { version: string; items: readonly { lead: string; children: readonly string[] }[] }[] = [
  {
    "version": "0.2.0",
    "items": [
      {
        "lead": "The Activity Overview nav panel arrived with three live tabs (Board, Unit treemap, Strip tiles), ported from the prototype generators.",
        "children": []
      },
      {
        "lead": "A fourth tab, Agent lanes, shows the thread-family tree as edge-less lane rows — a dot per thread, indent per depth level, project regions.",
        "children": []
      },
      {
        "lead": "A fifth tab, Activity flow, is the dive view: project → thread → turn → work, served by the new stateless `shape` RPC whose backend builds from live turn timelines.",
        "children": []
      },
      {
        "lead": "Activity flow rebuilt from nested lists into an Agent Graph-style tidy tree — node cards in depth columns, dashed bezier connectors, chevron folds, a status legend with counts, click-for-details in the footer, and double-click to open the thread.",
        "children": []
      },
      {
        "lead": "Activity flow gained fold scopes and filters.",
        "children": []
      },
      {
        "lead": "Every tab moved onto a map-style interface.",
        "children": []
      },
      {
        "lead": "The last camera now survives bb forward/back.",
        "children": []
      },
      {
        "lead": "The Activity flow's loading throbber is actually visible now.",
        "children": []
      },
      {
        "lead": "The Activity flow loading spinner is actually visible now.",
        "children": []
      },
      {
        "lead": "Views reflow to the measured panel width instead of packing into a fixed 1120px stage that forced horizontal scrolling.",
        "children": []
      },
      {
        "lead": "Board one-dot cards are at least 120px wide (wider slot grids), so short project names no longer truncate to a few characters.",
        "children": []
      },
      {
        "lead": "The legend now shows per-status counts with label sizes and contrast bumped (treemap labels 10px #98a8b6, board/tile labels 11px #9fb4c8).",
        "children": []
      },
      {
        "lead": "Thread timestamps aligned to the SDK's epoch-number types, leaving `tsc --noEmit` clean.",
        "children": []
      }
    ]
  }
];
